lists/urls.py
from django.conf.urls import url
from lists import views

urlpatterns = [
	url(r'^new$', views.new_list, name='new_list'),
	url(r'^(\d+)/$', views.view_list, name='view_list'),
	#url(r'^(\d+)/add_item$', views.add_item, name='add_item'),
	url(r'^personal$', views.personal, name='personal_home_page'),
]

superlists/urls.py
from django.conf.urls import include, url
from lists import views as list_views  #1
from lists import urls as list_urls  #2

urlpatterns = [
	url(r'^$', list_views.personal_home_page, name='home'),
	url(r'^lists/', include(list_urls)),
	# url(r'^admin/', include(admin.site.urls)),
]

lists/models.py
from django.db import models
from django.core.urlresolvers import reverse

# Create your models here.

class List(models.Model):
	def get_absolute_url(self):
		return reverse('view_list', args=[self.id])

class Item(models.Model):
	text = models.TextField(default='')
	list = models.ForeignKey(List, default=None)

lists/views.py
from django.core.exceptions import ValidationError
from django.shortcuts import redirect, render
from django.http import HttpResponse
from lists.models import Item, List
# Create your views here.
'''
def home_page(request):
	return render(request,'home.html')
'''	
def personal_home_page(request):
	'''
	if request.method == 'POST':
		Item.objects.create(text=request.POST['item_text'])
		return redirect('/lists/the-only-list-in-the-world/')
	
	kata = None
	jumlah_item = Item.objects.count()
	if jumlah_item == 0:
		kata = "yey, waktunya berlibur"	
	elif jumlah_item > 0 and jumlah_item < 5:
		kata = "sibuk tapi santai"
	elif jumlah_item >= 5:
		kata = "oh tidak"	
	items = Item.objects.all()
	'''
	kata = "yey, waktunya berlibur"
	return render(request, 'home.html',{'kata':kata})

def view_list(request, list_id):
	list_ = List.objects.get(id=list_id)
	jumlah_item = Item.objects.filter(list = list_.id).count()
	kata = None
	error = None
	#jumlah_item = Item.objects.count()
	if jumlah_item == 0:
		kata = "yey, waktunya berlibur"
	elif jumlah_item > 0 and jumlah_item < 5:
		kata = "sibuk tapi santai"
	elif jumlah_item >= 5:
		kata = "oh tidak"

	if request.method == 'POST':
		try:
			item = Item(text=request.POST['item_text'], list=list_)
			item.full_clean()
			item.save()
			return redirect(list_)
		except:
			error = "You can't have an empty list item"
	return render(request, 'list.html', {'list': list_,'kata':kata, 'error': error})

#def new_list(request):
#	list_ = List.objects.create()
#	Item.objects.create(text=request.POST['item_text'], list=list_)
#	return redirect('/lists/%d/' % (list_.id,))
	
def add_item(request,list_id):
	list_ = List.objects.get(id=list_id)
	Item.objects.create(text=request.POST['item_text'], list=list_)
	return redirect('/lists/%d/' % (list_.id,))
	
def personal(request):
	return render(request,'personal.html')

def new_list(request):
	list_ = List.objects.create()
	item = Item.objects.create(text=request.POST['item_text'], list=list_)
	try:
		item.full_clean()
		item.save()
	except ValidationError:
		list_.delete()
		error = "You can't have an empty list item"
		return render(request, 'home.html', {"error": error})	
	return redirect(list_)

lists/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Personal HomePage</title>
    <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/base.css" rel="stylesheet">
</head>
<body>
<div class="container">
	<div class="row">
		<div class="col-md-6 col-md-offset-3 jumbotron">
            		<div class="text-center">
			<h1>{% block header_text %}{% endblock %}</h1>
			<form method="POST" action="{% block form_action %}{% endblock %}">
			<input name="item_text" id="id_new_item" class="form-control input-lg" placeholder="Enter a to-do item" />
				{% csrf_token %}
				{% if error %}
					<div class="form-group has-error">
            					<span class="help-block">{{ error }}</span>
        				</div>
    				{% endif %}
			</form>
			</div>
		</div>
	</div>

	<div class="row">
		<div class="col-md-6 col-md-offset-3" >
			{% block table %}
			{% endblock %}
			{% block kata %}{% endblock %}
		</div>
	</div>
</div>
</body>
</html>

lists/templates/home.html
{% extends 'base.html' %}

{% block header_text %}Start a new To-Do list{% endblock %}

{% block form_action %}{% url 'new_list' %}{% endblock %}

{% block kata %} <p>komentar: {{kata}} </p> {% endblock %}

lists/templates/list.html
{% extends 'base.html' %}
{% block header_text %}Your To-Do list{% endblock %}
{% block form_action %}{% url 'view_list' list.id %}{% endblock %}
{% block table %}
<table id="id_list_table" class="table" >
	{% for item in list.item_set.all %}
		<tr><td>{{ forloop.counter }}: {{ item.text }}</td></tr>
	{% endfor %}	
</table>
{% endblock %}
{% block kata %}<p>komentar: {{kata}}</p>{% endblock %}

lists/templates/personal.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Personal Page Css Template</title>
<link rel="stylesheet" type="text/css" href="/static/style.css" media="screen" />
<!--[if IE 6]>
<link rel="stylesheet" type="text/css" href="iecss.css" />
<![endif]-->
</head>

<body>
<div id="main_container">

	<div id="header">
    	<div id="logo"><a href="home.html"><img src="/static/img/logo.png" width="358" height="40" alt="" title="" border="0" /></a></div>
    
        <!--div id="menu">
            <ul>                                              
                <li><a class="current" href="#" title="">home</a></li>
                <li><a href="#" title="">about me</a></li>
                <li><a href="#" title="">my photos</a></li>
                <li><a href="#" title="">my projects</a></li>
                <li><a href="#" title="">contact</a></li>
            </ul>
        </div-->
    
    </div>
    
    
    <div id="middle_box">
    	<div class="middle_box_content">
    	<div class="welcome_title"><img src="/static/img/welcome_title.gif" alt="" title="" /></div>
        <p class="about_text">
		"Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
        </p>
        <a href="#" class="more"><img src="/static/img/more_link.gif" alt="" title=""  border="0"/></a>
        </div>
    </div>
    
    <div id="center_content">
    
 			<div class="left_content">
				<div class="title_photos">My photos</div>	
                
 				<a href="#"><img src="/static/img/photo1.gif" alt="" title="" border="0" class="photo" /></a>
                <a href="#"><img src="/static/img/photo2.gif" alt="" title="" border="0" class="photo"/></a>
 
 				<div class="title_photos">My friends</div>
                      <div class="friends_list">
                    
                         <ul>                                              
                            <li><a href="#" title="">Sed ut perspiciatis unde omnis iste natus</a></li>
                            <li><a href="#" title="">Sed ut perspiciatis unde omnis iste natus</a></li>
                            <li><a href="#" title="">Sed ut perspiciatis unde omnis iste natus</a></li>
                            <li><a href="#" title="">Sed ut perspiciatis unde omnis iste natus</a></li>
                        </ul>           
                    
                    </div>                   

            </div>
            
            
            
            
            
 			<div class="right_content">
            <div class="title_journal">My journal</div>
				<div class="news_tab">
                <h1>Ut enim ad minim veniam</h1>
                <p>
"Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."</p>
                <div class="news_details"><span class="date">13.02.2008</span></div>
                </div>

 				<div class="news_tab">
                <h1>Ut enim ad minim veniam</h1>
                <p>
"Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."</p>
                <div class="news_details"><span class="date">13.02.2008</span></div>
                </div>
 
  				<div class="news_tab">
                <h1>Ut enim ad minim veniam</h1>
                <p>
"Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."</p>
                <div class="news_details"><span class="date">13.02.2008</span></div>
                </div>

                
            </div>            
            
            
        <div class="clear"></div>    
       </div>     
            
            
     <div id="footer">
     	<div class="copyright">
        <img src="/static/img/footer_logo.gif" alt="" title="" />
        </div>
    	<div class="footer_links">
        <a href="http://csstemplatesmarket.com"><img src="/static/img/csstemplatesmarket.gif" alt="csstemplatesmarket" title="csstemplatesmarket" border="0" /></a>
        </div>
    
    
    </div>



</div>
</body>
</html>